Quansight-Labs/quansight-labs-site

README.md
=> Update dev instructions to note the PyPI or conda packages.

.travis.yml, configs/atom.ini, configs/markdown-highlighter.ini, content/blog/contents.lr, qslabs_site.lektorproject, templates/layout.html
Tested locally; feed will show up at http://labs.quansight.org/blog/feed.xml
=> Blog: add Pygments highlighting and an Atom feed

.circleci/config.yml, .gitignore
=> Set up CircleCI.

posts/2019/04/metadsl.ipynb, posts/2019/05/metadsl.ipynb
In this post I give some motivation for metadsl and build up a simple example from scratch. It doesn't use metadsl, but is the same concept so the hope is it can give readers a feel for it, without introducing too much complexity.
=> Add  metadsl blog post

posts/2019/07/uarray-update-api-changes-overhead-and-comparison-to-__array_function__.ipynb
@teoliphant As requested, the comprehensive example of how to override NumPy with `uarray`, along with a motivation section.
=> Update uarray blog

posts/2019/09/ruby-wrappers-for-the-xnd-project.md
Post with a brief introduction to the XND Ruby wrapper.
=> add xnd ruby post

posts/2020/02/my-unexpected-dive-into-open-source-python.md
As I spoke to Ralf, this is a one-line text change in my blog post. The other changes is adding a line break after the images.
This time, the changes aren't also including the changes from joining-blog-post branch. The changes here are only what I've added today.
Should I only close the PR gh-53 once this PR is closed? Or should I close it now?
=> Fix typo in special thanks section

templates/book.tmpl
=> Add Google Analytics

.circleci/config.yml, conf.py, plugins/__init__.py, plugins/commonmark/README.md, plugins/commonmark/commonmark.plugin, plugins/commonmark/commonmark.py, plugins/commonmark/conf.py.sample, plugins/commonmark/requirements.txt, posts/2020/04/introducing-ndindex-a-python-library-for-manipulating-indices-of-ndarrays.markdown
Please review.
This also adds the commonmark extension, as it wasn't possible to format some of this with the default Markdown. Unfortunately, this disables syntax highlighting in the code cells. We can add highlight.js to the post if we want to re-add it. I played with it a bit but couldn't get it to get colors that looked good, so I didn't bother with it.
=> Add a post about ndindex

conf.py, templates/book.tmpl
Fixes https://github.com/Quansight-Labs/quansight-labs-site/pull/71
=> Add Google Analytics to head

posts/2020/06/portable-python-env.md
=> portable python

posts/2020/07/Three-months-and-having-fun.md
=> add post about me working at quansight

posts/2020/08/but-what-are-traitlets.md
Prompted by this thread https://twitter.com/jeremyphoward/status/1294115713594974208
=> Blog post: What are traitlets

.circleci/config.yml
Changes pip upgrade strategy to solve nikola build problem on CircleCI.
edit: still trying to figure out the right solution to pass both CircleCI and Netlify.
=> Tries to fix CircleCI build 

.circleci/config.yml
=> CI: fix Python version on CircleCI master branch deploy job

posts/2020/10/manylinux1-manylinux2010.md, posts/2020/11/manylinux1-manylinux2010.md
In one of the NumPy community meetings, someone asked why we are still shipping manylinux1 wheels. I promised to write a blog post. Here it is. I am not sure about the conda parts, help is welcome.
=> add manylinux blog post

posts/2020/11/the-ibis-backends.md
Here is a new version of @tonyfast's post on Ibis backends.  I used some html hacks and fixed up some other formatting.
=> Fix table and text.

posts/2020/11/the-ibis-backends.md
The title of the post is displayed twice.  I removed the title from the markdown text.
=> Ibisbackends new

.circleci/config.yml, .gitignore, Makefile, conf.py, pages/search.html, requirements.txt
as discussed on the qshare-tqz meeting this week. "European friendly" times make a difference!
=> Add the localsearch plugin

.circleci/config.yml
=> fix circleci deploy step

.circleci/config.yml
Redo #172 to activate the venv instead
=> activate the venv since 'deploy' requires PATH modification

.circleci/config.yml
=> Fix deployment to GitHub, remove stray venv command

.github/workflows/deploy.yml
From the documentation this should trigger on the last commit of the
default branch.
This will allow to schedule posts and have them auto published.
=> Rebuild the website daily.

themes/quansightlabs/assets/css/quansightlabs.css
Makes the header consistent between posts and other pages
On `master`:
This PR:
=> STY Makes the header consistent between posts and other pages

conf.py, themes/quansightlabs/assets/css/quansightlabs.css, themes/quansightlabs/templates/post_helper.tmpl
Closes https://github.com/Quansight-Labs/quansight-labs-site/issues/106
=> ENH Include logo in metadata

posts/2021/08/github-actions-benchmarks.md
This PR fixes the publication date on the blogpost so will be published on 18th Aug 2021
=> :pencil2: Fix publishing date - move backward

posts/2021/08/czi-eoss4-grants-at-quansight-labs.md
Previous discussion was in the hackmd
https://hackmd.io/whN3zt8FQECee-BkeyHRcQ
Text has been unchanged, except with the addition of links to the CZI pages.
=> Add CZI eoss4 grant announce.

README.md, requirements.txt
We can tag it as not to be installed.
=> Automatic handling of pyinotify on mac.

posts/2021/07/numpy-accessibility-guidelines.md
Small adjustment to place text under image
=> Adds newline to place text under image in Numpy Accessible blog post

README.md
Add GH actions badge to the repo for easy visibility
=> :memo: Add actions badge

posts/2021/08/low-code-workshop.md, posts/2021/09/low-code-workshop.md
hey friends. i'd like to submit this collaborative post on behalf of @isabela-pf @MarsBarLee and @melissawm . in this post we talk about a recently successful sprint for on boarding.
=> Alt text low code post

.github/workflows/pa11y_tests.yml, posts/2021/10/cxx-numba-interoperability.md, posts/2021/10/cxx2py.py, posts/2021/10/cxx2py_libfoo.cpp, posts/2021/10/libfoo.py
=> An efficient method of calling C++ functions from numba/Python using clang++/ctypes/rbc

themes/quansightlabs/assets/css/custom.css
@rgommers i cranked down the h1, h2 a bit. can you let me know if this resolves #281 ?
=> reduce h1, h2 font size

posts/2021/11/pydata-extensibility-vision.md
Updated the link to Scientific Python Discourse post.
=> Update link in pydata-extensibility-vision.md

netlify.toml
As recommended by Matthias this PR modifies our preview build command to allow for rendering of future dated posts
=> :construction_worker: Update netlify.toml to add preview of future posts

galleries/team/metadata.yml
This PR updates the projects in the team section of the site
=> :busts_in_silhouette: Update team section

requirements.txt
=> :arrow_up: Update dependencies

requirements.txt
Updating some dependencies again
=> :arrow_up: More dependencies

posts/2022/01/ipython-8.0-lessons-learned-maintaining-software.md
Minor blemish in an otherwise very enjoyable post.
=> DOC: Fix typo in IPython 8 post

posts/2020/03/documentation-as-a-way-to-build-community.md, posts/2020/12/jupyterlab-winter-theme.md, posts/2021/04/spot-the-differences.md
Updated tags for a few posts for improved indexing of design and documentation-related content.
=> Update post tags

migration/blogs_migration.py
As suggested by @gabalafou I've added my blog migration script here for and I will also share a zip of the output via slack so anyone can open PRs. There are a bunch(!) to do now but it is substantially less work per post (though it does still take some time :wink:  
Here is a description of the process I had with the last few posts:
0. create a branch blog-filename
1. Add the md file under posts/year/month
2. Add a description in the header (usually easy to do based on an intro line in the first paragraph)
3.  Images are added using a folder structure similar to what we had before, but instead of the images folder we have a public folder and each post has its own unique folder. The pattern is something like this: public/posts/year/month/blog-file-name-as-folder-name/hero.svg
3.1 Add the …
=> adding the blog migration script to the new website
