Quansight-Labs/quansight-labs-site

- conf.py
- pages/about.rst
- pages/index.rst
* Enables non-blog pages along with the blog posts. 
* Adds some example pages for the main page (`Home`) and about page (`About`).
* Point Blog section of the nav bar to the Blog index page instead of the Archive.
A preview:
> PR: Add non-blog config and some initial pages

- .circleci/config.yml
The release of 2 days ago seems to have broken redirects.
> MAINT: pin nikola version to most recent version that worked well.

- requirements.txt
Introduced in gh-85, need to be consistent with the CircleCI config
> Pin Nikola version to 8.0.4 in requirements.txt

- posts/2020/11/a-second-czi-grant-for-numpy-and-openblas.md
Now that [the announcement is live](https://chanzuckerberg.com/newsroom/czi-awards-4-7-million-for-open-source-software-and-organizations-advancing-open-science/), this can be published.
@rgommers can you please review?
> Adds post about second CZI grant for NumPy and OpenBLAS

- posts/2020/11/a-second-czi-grant-for-numpy-and-openblas.md
Make sure we have a link to the full proposal to ensure transparency.
> Adds link to full CZI proposal for NumPy, hosted on figshare.

- posts/2021/04/pytorch-tensoriterator-internals-update.md
Of course, the day the post goes live, one of the examples breaks. `make_reduction` no longer accepts undefined result tensors. This change is shown to fix the issue here: https://github.com/kurtamohler/pytorch-TensorIterator-examples/actions
cc @rgommers
> Fix example 5 code

- themes/quansightlabs/assets/css/custom.css
Using `text-align: justify` expands out the title and paragraphs to fit the width of the container:
This is easily seen with the title for https://github.com/Quansight-Labs/quansight-labs-site/pull/184:
> STY Use left justify left for post index

- pages/about.rst
- pages/index.rst
- pages/projects.rst
- pages/team.rst
- themes/quansightlabs/templates/post_header.tmpl
- themes/quansightlabs/templates/post_ipynb.tmpl
While looking at https://github.com/Quansight-Labs/quansight-labs-site/pull/200, I saw that the description was either non-descriptive or not present in the description metatag. This PR adds the description into the metatags.
> ENH Adds description into the metatags

- posts/2021/06/pytest-pytorch.ipynb
This is the official introduction of [`pytest-pytorch`](https://github.com/Quansight/pytest-pytorch) that will be linked from the PyTorch developer wiki.
> add blog post for `pytest-pytorch`

- .github/workflows/deploy.yml
Merging this will also release the Pyflyby blog post that _should_ already have been published.
> Allow to manually trigger rebuild

- conf.py
- posts/2020/11/design_in_open_source.md
- posts/2020/12/jupyterlab-winter-theme.md
- posts/2021/04/spot-the-differences.md
- posts/2021/07/better-interractive-jupyter-session-with-pyflyby.md
- requirements.txt
- themes/quansightlabs/templates/index.tmpl
- themes/quansightlabs/templates/post_header.tmpl
Multiple author support was added in nikola 8.1.2. This PR adds multiple author support to the labs website.
Before an "author" is the complete string defined by the metadata "author" tag:
With this PR every author gets their own author page:
> ENH Supports multiple authors

- posts/2021/07/moving-scipy-to-meson.md
Supporting @pradyunsg in the struggle against using PEP numbers instead of human-understandable terms.
> Minor wording fix, use "pyproject.toml-based builds", no PEP xxx

- conf.py
Before merging:
-- 
[Here](https://elegant-bhaskara-0c18b3.netlify.app/blog/2021/07/pyflyby-improving-efficiency-of-jupyter-interactive-sessions/) is how it looks like (on a fork of mine, with a different config to comment on a different repo), and [here is the issue](https://github.com/Carreau/quansight-labs-site/issues/2) the utterance bot create on the fork.
(You can try to comment on above demo deployment, but be carefull the redirect is incorrect, and you will need to mess with the URL once you've authorized github)
> Enable utterances (comment system) on the blog.

- README.md
The schedule is only available for quansight employees or other's who
have received invitations.
> Add link to schedule in the readme.

- posts/2021/08/czi-eoss4-grants-at-quansight-labs.md
Author list needs to be on a single line, the rest gets cut off.
> Fix author listing on EOSS cycle 4 blog post

- posts/2019/09/ruby-wrappers-for-the-xnd-project.md
- posts/2019/11/Files-Improvements.md
- posts/2020/03/documentation-as-a-way-to-build-community.md
- posts/2021/08/czi-eoss4-grants-at-quansight-labs.md
Making sure we are using & as separator, using full spelling of author
names with no other characters to make sure this page list authors only
once:
https://labs.quansight.org/authors/
@melissawm Just want to make sure it's the right fix, or do you prefer me to unify as "Melissa Mendonça" ?
> Unify author spelling.

- posts/2021/09/not-a-checklist.md
Related to #229
I forgot to put a `` tag to denote the end of my post's summary! Sorry about that, and thanks for pointing it out @rgommers.
Please let me know if it seems like I've missed anything else.
> Add teaser end tag Jupyter Accessibility Post 3

- posts/2021/09/low-code-workshop.md
Prevents duplication of the header in the [recent post](https://labs.quansight.org/blog/2021/09/low-code-contributions-through-GitHub/)
> Remove redundant markdown header in the recent low-code post

- posts/2019/10/quansight-labs-work-update-for-september-2019.md
While this is supported by docutils for historic reason it is not in the
spec and make it harder to parse for non-docutils parsers.
It also show the right ways to do things to users.
> Do not use space in directive.

- conf.py
- themes/quansightlabs/assets/css/custom.css
- themes/quansightlabs/templates/index.tmpl
this pull request will address a few outstanding issues. 
1. change the blog index to include a single h1 by replacing the blog posts with h2. this change is more compliant with WCAG.
2. style our link anchors to improve their visibility (resolve #110 )
we resolve this by adding underlines that are recommended in the mdn docs. https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links
3. considerations on the pygments theme
@rgommers @trallard we'll need to choose a theme to rectify the syntax highlighting problem in #176 . could y'all pick a pygments theme from https://help.farbox.com/pygments.html that you think is preferable. it turns out contrast for pygments has been a problem for a while https://maxchadwick.xyz/blog/syntax-highlighting-and-color-contrast-accessibil …
> modify labs styling

- posts/2022/02/jupyter-czi-accessibility-roadmap-announcement.md
I couldn't get the site to build locally, I was seeing an error for an invalid date - probably because this year we don't have Feb 29 :)
> Fix date on Jupyter CZI accessibility post

- themes/quansightlabs/assets/css/custom.css
This PR improves the style of the blog index for mobile (by removing some nested max-width in the CSS):
> STY Better mobile spacing

- plugins/errorpages/templates/jinja/404.tmpl
- plugins/errorpages/templates/mako/404.tmpl
Before this PR, the 404 page leaks the translation machinery, so you get a page with code in the h1 and div:
After this PR, you get a normal looking 404 that says "Not Found":
> Fix 404 pages
